language: node_js
sudo: no
dist: trusty
group: edge
node_js:
  - "8"
  - "10"
env:
  - CXX=g++-6 MONGODB=mongodb://127.0.0.1/test ES=127.0.0.1:9200
install:
  - find /usr -name '*poppler*.so*'
  - npm install -g npm@latest
  - npm install
  - npm install coveralls
  - npm install istanbul
services:
  - mongodb
  - elasticsearch
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - r-packages-trusty
      - mongodb-3.0-precise
      - elasticsearch-5.x
    packages:
      - g++-6
      - libpoppler-glib-dev
      - mongodb-org
      - elasticsearch
script:
  - ./test/perpareDatabase.sh && npm run coverage
  - cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
