sudo: no
dist: stretch
group: edge
services:
  - docker

script:
  - >
    git clean -dfx &&
    docker build . -t maowtm/schsrch --no-cache &&
    docker-compose -f docker-compose-example.yml up -d es mongo &&
    sleep 20 &&
    docker run --entrypoint=bash --user=www -t --network schsrch_mw -e NODE_ENV=development -e MONGODB=mongodb://mw-mongo/schsrch -e ES=mw-es:9200 -e SITE_ORIGIN=http://localhost -e COVERALLS_REPO_TOKEN=$COVERALLS_REPO_TOKEN -v $(pwd)/.git:/usr/src/app/.git maowtm/schsrch -c "npm install coveralls && npm install istanbul && test/perpareDatabase.sh && npm run coverage && cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js";
    if [ $? -ne 0 ]; then
      exit 1;
    fi;
    docker run --entrypoint=bash -t --network schsrch_mw -p 3000:80 -e NODE_ENV=production -e MONGODB=mongodb://mw-mongo/schsrch -e ES=mw-es:9200 -e SITE_ORIGIN=http://localhost maowtm/schsrch -c "node server.js" &
    sleep 10 &&
    curl -vI 'http://127.0.0.1:3000'

deploy:
  provider: script
  script: echo "$DOCKERHUB_PASSWORD" | docker login -u "maowtm" --password-stdin && docker push maowtm/schsrch
  on:
    branch: master
