version: '3'
networks:
  mw:
    driver: bridge
services:
  www:
    container_name: schsrch-www
    # build: .
    image: maowtm/schsrch
    networks:
      - mw
    ports:
      - "127.0.0.1:80:80"
      - "127.0.0.1:443:443"
      - "192.168.0.113:80:80"
      - "127.0.0.1:9229:9229" # for debugger
    environment:
      NODE_ENV: development
      MONGODB: mongodb://mw-mongo/schsrch
      ES: mw-es:9200
      SITE_ORIGIN: http://localhost
    stdin_open: true
    tty: true
    command: bash # After running "docker-compose -f docker-compose-example.yml up -d", run "docker attach schsrch-www" to get a shell and run "npm run webpack-dev &" and/or node server.js .
    depends_on:
      - mongo
      - es
    volumes:
      - ./index.js:/usr/src/app/index.js
      - ./view:/usr/src/app/view
      - ./test:/usr/src/app/test
      - ./lib:/usr/src/app/lib
      - /home/mao/active-projects/TransformationStage:/usr/src/app/node_modules/transformationstage
  mongo:
    container_name: mw-mongo
    image: mongo:latest
    networks:
      - mw
    volumes:
      - /data/db
      - /data/configdb
    command: ["--noauth"]
  es:
    container_name: mw-es
    image: docker.elastic.co/elasticsearch/elasticsearch:6.6.1
    networks:
      - mw
    volumes:
      - /usr/share/elasticsearch/data
