version: '3'
networks:
  mw:
    driver: bridge
services:
  www:
    container_name: schsrch-www
    # build: .
    image: maowtm/schsrch
    networks:
      - mw
    ports:
      - "127.0.0.1:80:80"
      - "127.0.0.1:443:443"
    environment:
      NODE_ENV: development
      MONGODB: mongodb://mw-mongo/schsrch
      ES: mw-es:9200
      SITE_ORIGIN: http://localhost
    stdin_open: true
    user: node:node
    tty: true
    depends_on:
      - mongo
      - es
  vscode-dev:
    container_name: schsrch-www-vscode
    # build: .
    image: maowtm/schsrch-dev
    networks:
      - mw
    environment:
      NODE_ENV: development
      MONGODB: mongodb://mw-mongo/schsrch
      ES: mw-es:9200
      SITE_ORIGIN: http://localhost
    stdin_open: true
    tty: true
    command: bash
    user: node:node
    depends_on:
      - mongo
      - es
    volumes:
      - .:/usr/src/app
  mongo:
    container_name: mw-mongo
    image: mongo:latest
    networks:
      - mw
    volumes:
      - /data/db
      - /data/configdb
    command: ["--noauth"]
  es:
    container_name: mw-es
    image: docker.elastic.co/elasticsearch/elasticsearch:6.6.1
    networks:
      - mw
    volumes:
      - /usr/share/elasticsearch/data
